#!/usr/bin/node

// prints My number: <first argument converted in integer> if the first argument can be converted to an integer
// If the argument can’t be converted to an integer, print “Not a number”

const argument = process.argv;
if (Number(argument[2])) {
        let i = 0
  while (i < argument[2]) {
    console.log('C is fun');
          i++;
  }
} else {
  console.log('Missing number of occurrences');
}
